# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QCommandLinkButton, QFrame,
    QGroupBox, QLCDNumber, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPlainTextEdit, QSizePolicy,
    QSlider, QStatusBar, QWidget)

class Ui_main_ui(object):
    def setupUi(self, main_ui):
        if not main_ui.objectName():
            main_ui.setObjectName(u"main_ui")
        main_ui.resize(800, 683)
        icon = QIcon()
        if QIcon.hasThemeIcon(QIcon.ThemeIcon.PrinterPrinting):
            icon = QIcon.fromTheme(QIcon.ThemeIcon.PrinterPrinting)
        else:
            icon.addFile(u"../static/icons/app_icon.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        main_ui.setWindowIcon(icon)
        main_ui.setIconSize(QSize(24, 19))
        self.centralwidget = QWidget(main_ui)
        self.centralwidget.setObjectName(u"centralwidget")
        self.text_group = QGroupBox(self.centralwidget)
        self.text_group.setObjectName(u"text_group")
        self.text_group.setGeometry(QRect(10, 20, 301, 261))
        self.text_group.setStyleSheet(u"background-color: rgb(246, 245, 244);")
        self.numbers = QPlainTextEdit(self.text_group)
        self.numbers.setObjectName(u"numbers")
        self.numbers.setGeometry(QRect(10, 30, 281, 141))
        self.number_limit = QSlider(self.text_group)
        self.number_limit.setObjectName(u"number_limit")
        self.number_limit.setGeometry(QRect(30, 214, 171, 31))
        self.number_limit.setMaximum(15)
        self.number_limit.setPageStep(5)
        self.number_limit.setValue(1)
        self.number_limit.setOrientation(Qt.Orientation.Horizontal)
        self.label = QLabel(self.text_group)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 180, 261, 31))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.number_limit_display = QLCDNumber(self.text_group)
        self.number_limit_display.setObjectName(u"number_limit_display")
        self.number_limit_display.setGeometry(QRect(230, 210, 61, 41))
        font = QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        self.number_limit_display.setFont(font)
        self.number_limit_display.setStyleSheet(u"color: rgb(41, 187, 39)")
        self.number_limit_display.setFrameShape(QFrame.Shape.Box)
        self.number_limit_display.setFrameShadow(QFrame.Shadow.Sunken)
        self.number_limit_display.setLineWidth(1)
        self.number_limit_display.setMidLineWidth(0)
        self.number_limit_display.setDigitCount(2)
        self.number_limit_display.setMode(QLCDNumber.Mode.Dec)
        self.number_limit_display.setSegmentStyle(QLCDNumber.SegmentStyle.Flat)
        self.site_content = QGroupBox(self.centralwidget)
        self.site_content.setObjectName(u"site_content")
        self.site_content.setGeometry(QRect(320, 10, 451, 271))
        self.site_content.setStyleSheet(u"background-color: rgb(246, 245, 244);")
        self.title = QLineEdit(self.site_content)
        self.title.setObjectName(u"title")
        self.title.setGeometry(QRect(20, 34, 401, 40))
        self.title.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.description = QLineEdit(self.site_content)
        self.description.setObjectName(u"description")
        self.description.setGeometry(QRect(20, 88, 401, 40))
        self.phone = QLineEdit(self.site_content)
        self.phone.setObjectName(u"phone")
        self.phone.setGeometry(QRect(20, 140, 401, 40))
        self.message = QLineEdit(self.site_content)
        self.message.setObjectName(u"message")
        self.message.setGeometry(QRect(20, 190, 401, 40))
        self.settings = QGroupBox(self.centralwidget)
        self.settings.setObjectName(u"settings")
        self.settings.setGeometry(QRect(10, 360, 761, 211))
        self.settings.setStyleSheet(u"background-color: rgb(246, 245, 244);")
        self.auto_crt_dir = QCheckBox(self.settings)
        self.auto_crt_dir.setObjectName(u"auto_crt_dir")
        self.auto_crt_dir.setGeometry(QRect(20, 40, 321, 24))
        self.auto_dir_cln = QCheckBox(self.settings)
        self.auto_dir_cln.setObjectName(u"auto_dir_cln")
        self.auto_dir_cln.setGeometry(QRect(20, 80, 291, 24))
        self.crm_drv_mng_sts = QCheckBox(self.settings)
        self.crm_drv_mng_sts.setObjectName(u"crm_drv_mng_sts")
        self.crm_drv_mng_sts.setGeometry(QRect(20, 120, 291, 24))
        self.headless_sts = QCheckBox(self.settings)
        self.headless_sts.setObjectName(u"headless_sts")
        self.headless_sts.setGeometry(QRect(20, 160, 251, 24))
        self.window_y = QLineEdit(self.settings)
        self.window_y.setObjectName(u"window_y")
        self.window_y.setGeometry(QRect(670, 40, 71, 26))
        self.window_x = QLineEdit(self.settings)
        self.window_x.setObjectName(u"window_x")
        self.window_x.setGeometry(QRect(570, 40, 71, 26))
        self.label_2 = QLabel(self.settings)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(650, 44, 16, 18))
        self.label_3 = QLabel(self.settings)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(420, 40, 121, 21))
        self.chrome_drv_path = QLineEdit(self.settings)
        self.chrome_drv_path.setObjectName(u"chrome_drv_path")
        self.chrome_drv_path.setGeometry(QRect(420, 80, 321, 26))
        self.screenshot_filename = QLineEdit(self.settings)
        self.screenshot_filename.setObjectName(u"screenshot_filename")
        self.screenshot_filename.setGeometry(QRect(420, 120, 321, 26))
        self.output_path_name = QLineEdit(self.settings)
        self.output_path_name.setObjectName(u"output_path_name")
        self.output_path_name.setGeometry(QRect(420, 160, 321, 26))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 280, 761, 71))
        self.terminal = QPlainTextEdit(self.groupBox_2)
        self.terminal.setObjectName(u"terminal")
        self.terminal.setGeometry(QRect(10, 25, 741, 41))
        self.start_app_button = QCommandLinkButton(self.centralwidget)
        self.start_app_button.setObjectName(u"start_app_button")
        self.start_app_button.setGeometry(QRect(590, 580, 176, 61))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setBold(True)
        self.start_app_button.setFont(font1)
        self.start_app_button.setStyleSheet(u"background-color: rgb(143, 240, 164);\n"
"alternate-background-color: rgb(192, 191, 188);\n"
"border-color: rgb(192, 191, 188);")
        self.start_app_button.setIconSize(QSize(55, 38))
        main_ui.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(main_ui)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 23))
        main_ui.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(main_ui)
        self.statusbar.setObjectName(u"statusbar")
        main_ui.setStatusBar(self.statusbar)

        self.retranslateUi(main_ui)

        QMetaObject.connectSlotsByName(main_ui)
    # setupUi

    def retranslateUi(self, main_ui):
        main_ui.setWindowTitle(QCoreApplication.translate("main_ui", u"MainWindow", None))
        self.text_group.setTitle(QCoreApplication.translate("main_ui", u"N\u00f6mr\u0259l\u0259rin siyah\u0131s\u0131", None))
        self.label.setText(QCoreApplication.translate("main_ui", u"G\u00f6st\u0259ril\u0259c\u0259k n\u00f6mr\u0259 limiti", None))
        self.site_content.setTitle(QCoreApplication.translate("main_ui", u"S\u0259hif\u0259 m\u0259zmunu", None))
        self.title.setPlaceholderText(QCoreApplication.translate("main_ui", u"Ba\u015fl\u0131q", None))
        self.description.setPlaceholderText(QCoreApplication.translate("main_ui", u"A\u00e7\u0131qlama", None))
        self.phone.setPlaceholderText(QCoreApplication.translate("main_ui", u"\u018flaq\u0259 n\u00f6mr\u0259si", None))
        self.message.setPlaceholderText(QCoreApplication.translate("main_ui", u"M\u0259tn", None))
        self.settings.setTitle(QCoreApplication.translate("main_ui", u"Ayarlar", None))
        self.auto_crt_dir.setText(QCoreApplication.translate("main_ui", u"\u00c7\u0131xar\u0131\u015f qovlu\u011fu yoxdursa avtomatik yarat", None))
        self.auto_dir_cln.setText(QCoreApplication.translate("main_ui", u"\u00c7\u0131xar\u0131\u015f qovlu\u011fundaki fayllar\u0131 sil", None))
        self.crm_drv_mng_sts.setText(QCoreApplication.translate("main_ui", u"Chrome Drive Manageri aktiv et", None))
        self.headless_sts.setText(QCoreApplication.translate("main_ui", u"Headless modu aktiv et", None))
        self.label_2.setText(QCoreApplication.translate("main_ui", u"X", None))
        self.label_3.setText(QCoreApplication.translate("main_ui", u"Ekran \u00f6l\u00e7\u00fcs\u00fc:", None))
        self.chrome_drv_path.setPlaceholderText(QCoreApplication.translate("main_ui", u"ChromeDriver yolu", None))
        self.screenshot_filename.setPlaceholderText(QCoreApplication.translate("main_ui", u"\u00c7\u0131xar\u0131\u015f fayllar\u0131n\u0131n ad\u0131", None))
        self.output_path_name.setPlaceholderText(QCoreApplication.translate("main_ui", u"\u00c7\u0131xar\u0131\u015f qovlu\u011funun ad\u0131", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("main_ui", u"Terminal", None))
        self.start_app_button.setText(QCoreApplication.translate("main_ui", u"Ba\u015fla", None))
    # retranslateUi

